---
name: Test JMeter Action

on:
  push:
    branches:
      - main
      
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run JMeter Tests
        uses: ./
        with:
          test-plan-path: ./tests/sample_test.jmx
          args: ""
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
