---
name: Test JMeter Action

on:
  push:
    branches:
      - main

jobs:

  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: tests/sample_test.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"
          
      - uses: actions/upload-artifact@v3
        with:
          name: jmeter-test-results
          path: reports/

